language: generic
sudo: required
services: 
  - docker

before install: 
  - docker build -t wouterdurwael/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true wouterdurwael/docker-react npm run test